<?php

namespace common\models;

use Yii;
use yii\db\Expression;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "stack".
 *
 * @property integer $id
 * @property string $name
 * @property string $code
 * @property integer $status
 * @property string $price
 * @property string $created_at
 * @property string $updated_at
 *
 * @property StackTransaction[] $stackTransactions
 * @property StackTrends[] $stackTrends
 */
class Stack extends ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'stack';
    }

    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'value' => new Expression('NOW()'),
            ],
        ];
    }

    public function afterSave($insert, $changedAttributes)
    {
        if ($this->isNewRecord) {
            Yii::$app->cache->delete("STACK_CODES");
            Yii::$app->cache->delete("STACK_NAMES");
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'code', 'status', 'price'], 'required'],
            [['status'], 'integer'],
            [['price'], 'number'],
            [['created_at', 'updated_at'], 'safe'],
            [['name'], 'string', 'max' => 250],
            [['code'], 'string', 'max' => 100]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', 'Name'),
            'code' => Yii::t('app', 'Code'),
            'status' => Yii::t('app', 'Stack Status'),
            'price' => Yii::t('app', 'Price'),
            'created_at' => Yii::t('app', 'Stack Created At'),
            'updated_at' => Yii::t('app', 'Stack Updated At'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStackTransactions()
    {
        return $this->hasMany(StackTransaction::className(), ['stack_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStackTrends()
    {
        return $this->hasMany(StackTrends::className(), ['stack_id' => 'id']);
    }

    public static function getStackOptions()
    {
        $stacks = Stack::findAll(array('status' => 0));
        return ArrayHelper::map($stacks, 'code', 'code');
    }

    public static function getStackCodeOptions()
    {
        $key = 'STACK_CODES';

        $stacks = json_decode(Yii::$app->cache->get($key), true);
        if (!$stacks || !count($stacks)) {
            $stacks = Stack::find()->all();
            $stacks = ArrayHelper::map($stacks, 'id', 'code');
            Yii::$app->cache->set($key, json_encode($stacks), 365*24*60*60*60);
        }

        return $stacks;
    }

    public static function getStackNameOptions()
    {
        $key = 'STACK_NAMES';

        $stacks = json_decode(Yii::$app->cache->get($key), true);
        if (!$stacks) {
            $stacks = Stack::find()->all();
            $stacks = ArrayHelper::map($stacks, 'id', 'name');
            Yii::$app->cache->set($key, json_encode($stacks), 365*24*60*60*60);
        }

        return $stacks;
    }

    public static function getPrice($stack_id)
    {
        $price = Yii::$app->cache->get('STACK_' . $stack_id);

        if (!$price) {
            $stack = Stack::findOne($stack_id);
            $price = $stack ? $stack->price : 0;
            if ($price) {
                Yii::$app->cache->set('STACK_' . $stack_id, $price, 24*60*60*60);
            }
        }

        return $price;
    }

}
